theme: jekyll-theme-cayman

github:
  is_project_page: false
  show_discord: false
  discord_url: "https://discord.gg/wU7gCkM"
  submit_run_url: "https://forms.gle/hHda5Qc1Fa8ozx5f7"
  suggest_category_url: "https://forms.gle/SrYrvaDFVL6XuNJi8"
